### PR TITLE
Added HTML templates

### PR DESCRIPTION
**Pull request by e5l**
Added template and slot elements.

### CODE REVIEW

**Comment by morki** [comment]
@e5l it looks ok :+1:

**Comment by matusekma** [comment]
Hi @morki,
when will this be released?
Thank you!

**Comment by asm0dey** [comment]
Hey, how do we use them?

**Comment by markth0mas** [comment]
> Hey, how do we use them?

There are some examples on the MDN: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_templates_and_slots

**Pull request merged**
